### ISSUE TITLE
List of missing implementations

### ISSUE THREAD

**Issue by schildbach** [public-transport/hafas-client#100]
I just compared what networks are supported by hafas-client and which by public-transport-enabler's HCI implementation and here are the ones that are missing:

- [ ] AVV Aachen
- [ ] DSB Denmark
- [ ] INVG Ingolstadt – #94
- [x] Luxemburg (CFL)
- [x] NVV Nordhessen – #114
- [ ] SE Sweden
- [ ] SNCB Belgium
- [ ] VAO Österreich
- [ ] VBN Bremen, Hamburg – [`vbn`](https://github.com/public-transport/hafas-client/tree/vbn)
- [ ] ZVV Zürich

**Comment by derhuerst** [comment]
Thanks!

**Comment by paha77** [comment]
What about SVV (Salzburg, Austria)? I know earlier it was supported.  Thank you.

**Comment by derhuerst** [comment]
Closing in favour of #41.
