### ISSUE TITLE
Journeys spanning multiple days fail to parse correctly with tzOffset !== null

### ISSUE THREAD

**Issue by TheZenti** [public-transport/hafas-client#106]
When querying a journey which spans multiple days while `tzOffset` is given in the HAFAS response, `daysOffset` isn't respected anymore.

The problem is probably at parse/date-time.js: https://github.com/public-transport/hafas-client/blob/29aea9a5efb7121e0ad73ca8ad1fb16c22cf6e34/parse/date-time.js#L28-L41

If `tzOffset === null`. `daysOffset` will be used to increment the day. If `tzOffset !== null`, `daysOffset` is ignored altogether.

Example raw output from HAFAS with a journey query from München Hbf (8000261) to Hausham (8002667) exhibiting that problem is at https://gist.github.com/TheZenti/b8ccd42a98c5a05b61c136754c958b8a.

The last journey starts on 2019-03-17, and ends on 2019-03-18. hafas-client however does not reflect that fact: https://gist.github.com/TheZenti/92410a452306c8df4f2b354a3cfa243f#file-hafas-client-output-js-L817-L818

**Comment by derhuerst** [comment]
Thanks for the report! I know there's a reason why `hafas-client` ignores `daysOffset` on `tzOffset !== null`, but don't remember the specific reason. I will change it and see if we notice another error.

**Comment by derhuerst** [comment]
Thinking about the semantics of the fields returned by HAFAS, I noticed that [*some* trains don't take the Daylight Saving Time into account](https://gist.github.com/derhuerst/938adbf7b63dd65ccd766920b29624df). So `daysOffset` + `tzOffset` will be broken in these specific cases. 💩

**Comment by derhuerst** [comment]
I've found a way to fix this using Luxon. Published as `hafas-client@4.0.1`.

**Comment by TheZenti** [comment]
Thanks!
