### ISSUE TITLE
DB: Support new DB.R19.04.a features

### ISSUE THREAD

**Issue by TheZenti** [public-transport/hafas-client#111]
Since April 2019, DB Navigator and bahn.de use DB.R19.04.a  as API ext.
This adds "Auslastungsinformation" (demand in English), as mentioned on [inside.bahn.de]( https://inside.bahn.de/db-navigator-funktionen/#Auslastungsanzeige) and [bahn.de](https://www.bahn.de/p/view/service/buchung/auslastungsinformation.shtml)

Using DB.R19.04.a in hafas-client returns this information as tcocL, with references from the journeys as dTrnCmpSX.tcocX.

JSON from refreshJourney: https://gist.github.com/TheZenti/12c3d8323c7a357774c1906545f31ecc#file-journeydetails-withload-json-L252
When using departures:
https://gist.github.com/TheZenti/12c3d8323c7a357774c1906545f31ecc#file-journeydetails-withload-json-L252

I've already started implementing rudimentary support for this in [my own fork](https://github.com/TheZenti/hafas-client), but it would be nice if hafas-client officially supports this ;)

I'm not sure if there are more new features, or if some got removed. I haven't taken a look at that yet.

**Comment by derhuerst** [comment]
Cool, thank you for pointing this out!

I took the commits from your fork and adapted them slightly, ending up with c49e543 on the `db-auslastung` branch. I'll merge it soon.

**Comment by derhuerst** [comment]
@schildbach Are you aware of any features they the DB endpoint added or removed recently?

**Comment by schildbach** [comment]
No.

I must admit I never understood what the API ext is meant for, until I read this issue. Rest assured I'm following this repository closely.

**Comment by TheZenti** [comment]
@derhuerst Awesome, thank you!
