### ISSUE TITLE
don't ignore scheduled/actual platform information on legs

### ISSUE THREAD

**Issue by juliuste** [public-transport/hafas-client#116]
While we use both `aPlatfR` and `aPlatfS` (same for `dPlat…`) on `stopovers`, we don't properly parse them yet for legs, which leads to inconsistent information in journeys that have platform changes, for example:

```js
{
    // …
    "direction": "Hamm(Westf)",
    "departurePlatform": "19",
    "arrivalPlatform": "6",
    "stopovers": [
        {
            // …
            "arrival": null,
            "arrivalDelay": null,
            "arrivalPlatform": null,
            "departure": "2019-05-28T18:16:00+02:00",
            "departureDelay": null,
            "departurePlatform": "18",
            "scheduledDeparturePlatform": "19",
            "remarks": []
        }
        // …
    ]
}
```

We could probably copy the following logic used in `/parse/stopover.js` to `/parse/journey-leg.js`:

```js
if (st.aPlatfR && st.aPlatfS && st.aPlatfR !== st.aPlatfS) {
	res.scheduledArrivalPlatform = st.aPlatfS
}
if (st.dPlatfR && st.dPlatfS && st.dPlatfR !== st.dPlatfS) {
	res.scheduledDeparturePlatform = st.dPlatfS
}
```

**Comment by juliuste** [comment]
Will work on this later today.

**Comment by derhuerst** [comment]
> We could probably copy the following logic [...].

Up to you, you can also move it into a shared function.

**Comment by juliuste** [comment]
Yes, I‘ll see what fits best. By "copying", I basically meant "using the same logic"y
