### ISSUE TITLE
leg.reachable breaks all journeys with walking leg

### ISSUE THREAD

**Issue by TheZenti** [public-transport/hafas-client#119]
When querying journeys where a leg involves walking, `pt.jny` will not exist. parseJourneyLeg will reliably error out in these cases.
https://github.com/public-transport/hafas-client/blob/f04b5416e4af7f7bbf0ec679e181611c3ae36fe6/parse/journey-leg.js#L59

For reproduction, you can use `client.journeys('8004019', '8098160', {results: 5})`, which will return journeys from Miesbach to Berlin Hbf. At Munich, there will always be a walking leg to change from platforms 27-36 to platforms 11-26.

**Comment by juliuste** [comment]
Sorry about that, I definitely need to work on fixing the tests so that we can catch obvious mistakes like this more reliably.

**Comment by TheZenti** [comment]
No problem, thanks for fixing it so quickly!

**Comment by juliuste** [comment]
I just published `4.2.1` on npm, please re-open if the issue persists.

**Comment by juliuste** [comment]
I'll notify you as soon as `4.2.1` is published on npm, for now you could pin hafas-client to the last working version (`4.1.1`).

**Comment by juliuste** [comment]
Published `4.2.1` now 🙂
