### ISSUE TITLE
Unable to generate the correct Checksum from App

### ISSUE THREAD

**Issue by Logxn** [public-transport/hafas-client#137]
Hello,

I have recorded API requests from the DB Navigator App in order to check my checksum implementation.

This was the body that has been sent via the app
```
{
   "client":{
      "os":"iOS 13.1.1",
      "id":"DB",
      "v":"19040000",
      "type":"IPH",
      "name":"DB Navigator"
   },
   "lang":"en",
   "ext":"DB.R19.04.a",
   "ver":"1.15",
   "svcReqL":[
      {
         "req":{
            "input":{
               "loc":{
                  "name":"illes?",
                  "type":"ALL"
               },
               "field":"S"
            }
         },
         "meth":"LocMatch"
      }
   ],
   "auth":{
      "aid":"n91dB8Z77MLdoR0K",
      "type":"AID"
   }
}
```

According to this "formula" ```md5(md5(requestString)+salt)``` and the correct salt 'bdI8UVj40K5fvxwf' I should get the checksum from above.

But somehow using this hash-routine:
```csharp
        public static string CalculateMD5Hash(string input)
        {
            // step 1, calculate MD5 hash from input
            MD5 md5 = System.Security.Cryptography.MD5.Create();
            byte[] inputBytes = System.Text.Encoding.UTF8.GetBytes(input);
            byte[] hash = md5.ComputeHash(inputBytes);

            // step 2, convert byte array to hex string
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i].ToString("X2"));
            }
            return sb.ToString();
        }

        public static string GenerateChecksum(string input)
        {
            // Body
            var body = CalculateMD5Hash(input);
            // BodyHash + Salt Raw
            var checksum = CalculateMD5Hash(x + DecryptSalt());

            return checksum;
        }
```
I do not get the correct hash.

Any clues or ideas?

**Comment by Logxn** [comment]
Info: You can reproduce it by typing "Illes" in the destination station and waiting for it to suggest you names

**Comment by derhuerst** [comment]
Thanks for reporting!

First of all, it could theoretically be that they changed the salt in recent versions of DB Navigator. Did you check that?

Unfortunately I can't help with Java crypto code, but hopefully somebody can help here. @alexander-albers can you help here?

Some more resources:

- the (working) `hafts-client` implementation:
    - the salt at https://github.com/public-transport/hafas-client/blob/2993cc0e87ddf52ba8b8e1b2337be3fc702e1c62/p/db/index.js#L376
    - the `mac` computation at https://github.com/public-transport/hafas-client/blob/2993cc0e87ddf52ba8b8e1b2337be3fc702e1c62/lib/request.js#L65-L72
- the original discussion: https://github.com/schildbach/public-transport-enabler/issues/187
- some old Gist showing the auth mechanism: https://gist.github.com/derhuerst/bc342b5f7acc6516757a8bf4b4ca803f
- Java & JS code to decrypt the encrypted Salt extracted from the app: https://gist.github.com/derhuerst/81a7d6a7298c16c3c68e6d54fd80755f

**Comment by schildbach** [comment]
The pte implementation still works – or am I missing something?

**Comment by derhuerst** [comment]
> The pte implementation still works – or am I missing something?

I assume this is only about the problems @Logxn with their implementation.

@Logxn Please check if you didn't confuse hex/UTF-8 encoding at some point. AFAICT you have to read the `mic` hex string as UTF-8.

**Comment by Logxn** [comment]
```csharp
private static string DecryptSalt()
        {
            string salt = null;

            using (var aes = Aes.Create())
            { 
                if (aes != null)
                {
                    // Hardcoded key extracted from APK
                    aes.Key = new byte[] {97, 72, 54, 70, 56, 122, 82, 117, 105, 66, 110, 109, 51, 51, 102, 85};
                    aes.IV = new byte[16];

                    var decryptor = aes.CreateDecryptor(aes.Key, aes.IV);

                    // This cipher is the checksum delivered with the app bundle
                    var cipher = Convert.FromBase64String("rGhXPq+xAlvJd8T8cMnojdD0IoaOY53X7DPAbcXYe5g=");
                    using (var memStream = new MemoryStream(cipher))
                    {
                        using (var cryptoStream = new CryptoStream(memStream, decryptor, CryptoStreamMode.Read))
                        {
                            using (var streamReader = new StreamReader(cryptoStream))
                            {
                                salt = streamReader.ReadToEnd();
                            }
                        }
                    }
                }
            }

            Console.WriteLine($"Salt Decrypted -> {salt}");

            return salt;
        }
```
This is my salt decryption, so that definitely checks out.

Tried almost everything.
Hashing the requestString converting the resulting bytes to a string.
That hashing the resulting string + salt and converting the output bytes to a new string together.

concating the bytes of the requestStringHash with the bytes of the salt and hashing that and create a new string out of it.

I am confused

**Comment by derhuerst** [comment]
Please check if the `public-transport-enabler` implementation works for you.

**Comment by Logxn** [comment]
I read that the requestString is supposed to be in hex format. Yet I dont see a 0x prefix in the original issue post. Do I need to remove it? I always do md5(0xfoobar + salt)

**Comment by Logxn** [comment]
So I tried everything I possibly could, even online md5 utf8 hashers, seems like I cant get the correct checksum. Could it be the salt changed or they add something new to the checksum?

**Comment by derhuerst** [comment]
Please use the code of `public-transport-enabler` or `hafas-client` and check if it works for you. After you have confirmed that, you can write your own implementation.

**Comment by Logxn** [comment]
So this is your code @derhuerst and since I didn't have time to set up my own node environment I did it online via repl.it

this is the code I used

```js
const createHash = require('create-hash')
const https = require('https');
const md5 = input => createHash('md5').update(input).digest()

// this is the requestString that should be hashed
https.get('https://gist.githubusercontent.com/Logxn/66b727c3c3b62fc5b68bd8f280a5fdb0/raw/f10db5f35a6f6003d773e43b7b818219234797bb/gistfile1.txt', (resp) => {
  let data = '';

  // A chunk of data has been recieved.
  resp.on('data', (chunk) => {
    data += chunk;
  });

  // The whole response has been received. Print out the result.
  resp.on('end', () => {

   const mic = md5(Buffer.from(data, 'utf8'))
   

   const micAsHex = Buffer.from(mic.toString('hex'), 'utf8')
   console.log("Request Data:\n"+data);

   console.log("md5 of requestString: " + mic.toString('hex') + "\n")

   const mac = md5(Buffer.concat([micAsHex, Buffer.from('bdI8UVj40K5fvxwf')]));
   console.log("checksum: " + mac.toString('hex') + "\n");
  });

}).on("error", (err) => {

});
```

This is the output:

![output1](https://i.imgur.com/qOecgQu.png)

If I use a wrapped format of the requestString then this is the following output:

![outputWrapped](https://i.imgur.com/fGrNEoe.png)

Which does not match the expected checksum of ```f715e40d9d22a069650e67631d7ff71f```


Also notice the difference check:
![diffChecker](https://i.imgur.com/o4RU07g.png)

**Comment by derhuerst** [comment]
> So this is your code @derhuerst and since I didn't have time to set up my own node environment I did it online via repl.it

It computed a different hash/checksum because the input doesn't contain line breaks:

```shell
$ curl -s 'https://gist.githubusercontent.com/Logxn/66b727c3c3b62fc5b68bd8f280a5fdb0/raw/f10db5f35a6f6003d773e43b7b818219234797bb/gistfile1.txt' | xxd
00000000: 7b22 636c 6965 6e74 223a 7b22 6f73 223a  {"client":{"os":
00000010: 2269 4f53 2031 332e 312e 3222 2c22 6964  "iOS 13.1.2","id
00000020: 223a 2244 4222 2c22 7622 3a22 3139 3034  ":"DB","v":"1904
00000030: 3030 3030 222c 2274 7970 6522 3a22 4950  0000","type":"IP
00000040: 4822 2c22 6e61 6d65 223a 2244 4220 4e61  H","name":"DB Na
00000050: 7669 6761 746f 7222 7d2c 226c 616e 6722  vigator"},"lang"
00000060: 3a22 656e 222c 2265 7874 223a 2244 422e  :"en","ext":"DB.
00000070: 5231 392e 3034 2e61 222c 2276 6572 223a  R19.04.a","ver":
00000080: 2231 2e31 3522 2c22 7376 6352 6571 4c22  "1.15","svcReqL"
00000090: 3a5b 7b22 7265 7122 3a7b 2269 6e70 7574  :[{"req":{"input
000000a0: 223a 7b22 6c6f 6322 3a7b 226e 616d 6522  ":{"loc":{"name"
000000b0: 3a22 696c 6c65 733f 222c 2274 7970 6522  :"illes?","type"
000000c0: 3a22 414c 4c22 7d2c 2266 6965 6c64 223a  :"ALL"},"field":
000000d0: 2253 227d 7d2c 226d 6574 6822 3a22 4c6f  "S"}},"meth":"Lo
000000e0: 634d 6174 6368 227d 5d2c 2261 7574 6822  cMatch"}],"auth"
000000f0: 3a7b 2261 6964 223a 226e 3931 6442 385a  :{"aid":"n91dB8Z
00000100: 3737 4d4c 646f 5230 4b22 2c22 7479 7065  77MLdoR0K","type
00000110: 223a 2241 4944 227d 7d                   ":"AID"}}
```

```shell
$ pbpaste | xxd
00000000: 7b0a 2020 2022 636c 6965 6e74 223a 7b0a  {.   "client":{.
00000010: 2020 2020 2020 226f 7322 3a22 694f 5320        "os":"iOS 
00000020: 3133 2e31 2e31 222c 0a20 2020 2020 2022  13.1.1",.      "
00000030: 6964 223a 2244 4222 2c0a 2020 2020 2020  id":"DB",.      
00000040: 2276 223a 2231 3930 3430 3030 3022 2c0a  "v":"19040000",.
00000050: 2020 2020 2020 2274 7970 6522 3a22 4950        "type":"IP
00000060: 4822 2c0a 2020 2020 2020 226e 616d 6522  H",.      "name"
00000070: 3a22 4442 204e 6176 6967 6174 6f72 220a  :"DB Navigator".
00000080: 2020 207d 2c0a 2020 2022 6c61 6e67 223a     },.   "lang":
00000090: 2265 6e22 2c0a 2020 2022 6578 7422 3a22  "en",.   "ext":"
000000a0: 4442 2e52 3139 2e30 342e 6122 2c0a 2020  DB.R19.04.a",.  
000000b0: 2022 7665 7222 3a22 312e 3135 222c 0a20   "ver":"1.15",. 
000000c0: 2020 2273 7663 5265 714c 223a 5b0a 2020    "svcReqL":[.  
000000d0: 2020 2020 7b0a 2020 2020 2020 2020 2022      {.         "
000000e0: 7265 7122 3a7b 0a20 2020 2020 2020 2020  req":{.         
000000f0: 2020 2022 696e 7075 7422 3a7b 0a20 2020     "input":{.   
00000100: 2020 2020 2020 2020 2020 2020 226c 6f63              "loc
00000110: 223a 7b0a 2020 2020 2020 2020 2020 2020  ":{.            
00000120: 2020 2020 2020 226e 616d 6522 3a22 696c        "name":"il
00000130: 6c65 733f 222c 0a20 2020 2020 2020 2020  les?",.         
00000140: 2020 2020 2020 2020 2022 7479 7065 223a           "type":
00000150: 2241 4c4c 220a 2020 2020 2020 2020 2020  "ALL".          
00000160: 2020 2020 207d 2c0a 2020 2020 2020 2020       },.        
00000170: 2020 2020 2020 2022 6669 656c 6422 3a22         "field":"
00000180: 5322 0a20 2020 2020 2020 2020 2020 207d  S".            }
00000190: 0a20 2020 2020 2020 2020 7d2c 0a20 2020  .         },.   
000001a0: 2020 2020 2020 226d 6574 6822 3a22 4c6f        "meth":"Lo
000001b0: 634d 6174 6368 220a 2020 2020 2020 7d0a  cMatch".      }.
000001c0: 2020 205d 2c0a 2020 2022 6175 7468 223a     ],.   "auth":
000001d0: 7b0a 2020 2020 2020 2261 6964 223a 226e  {.      "aid":"n
000001e0: 3931 6442 385a 3737 4d4c 646f 5230 4b22  91dB8Z77MLdoR0K"
000001f0: 2c0a 2020 2020 2020 2274 7970 6522 3a22  ,.      "type":"
00000200: 4149 4422 0a20 2020 7d0a 7d              AID".   }.}
```

You should be able to use the hash/checksum with the body from the Gist and get a response from HAFAS.

**Comment by Logxn** [comment]
Uhm nope, I seem to be getting an internal server error. (I may be missing a header tho?)

**Comment by Logxn** [comment]
Update: Tried using the checksum generated by the nodejs code I used above, it didn't work.
Still receiving a Internal Server error

**Comment by Logxn** [comment]
Also using the non wrapped body:

```json
{"client":{"os":"iOS 13.1.2","id":"DB","v":"19040000","type":"IPH","name":"DB Navigator"},"lang":"en","ext":"DB.R19.04.a","ver":"1.15","svcReqL":[{"req":{"input":{"loc":{"name":"illes?","type":"ALL"},"field":"S"}},"meth":"LocMatch"}],"auth":{"aid":"n91dB8Z77MLdoR0K","type":"AID"}}
```

with the checksum generated by the app: ```f715e40d9d22a069650e67631d7ff71f``` works perfectly.
So either the checksum generation changed (since I get a different checksum from your code too) or they do something different on the iOS Application

**Comment by derhuerst** [comment]
I can't follow you TBH. If you get an internal server error, that could also be because of other reasons than the checksum calculation. Debugging your setup (or figuring out that the checksum calculation logic indeed changed) step by step is a very slow process.

Again, **I suggest you to work your way backwards from a working implementation**, i.e. `hafas-client`, `public-transport-enabler` or [`TripKit`](https://github.com/alexander-albers/tripkit), whatever language you are most familiar with. All three should work: Given a request, they should wrap it correctly and generate the right checksum.

What do you actually want to do? If you just want to query data, why don't you use one of the existing libraries? Do you want to port them to another language/stack?

**Comment by Logxn** [comment]
So since my explanation in english seems to be crappy we don't we try it in german?

Ich versuche die API auf .NET zu porten für meinen eigenen gebrauch. (Und weil mir C# einfach mehr liegt als die Sprachen, die dort verwendet werden)

Mein Problem ist, dass die cheksum die ich über ein MITM attack gesniffed habe nicht dem entspricht die ich generiere.

Das macht mich stutzig, denn eigentlich sollte folgende "Formel" gelten md5(md5(requestString) + salt).
Da du mir des öfteren Vorgeschlagen hast ich soll doch mal den Code von euch probieren habe ich das in einem online nodejs compiler getan.

Egal welche Art von Request string (einzeiler oder formatiert) ich dort benutze, bekomme ich einen anderen Hash als von der App gegeben.

Hier ist meine Request "Logik"
```csharp
// Erstellung eines StationRequest JSON Objects
            // Dieses Object ist auch 100% richtig (verglichen via diffchecker.com)
            var stationRequest = new StationRequest
            {
                Auth = new AuthenticationObject(),
                SerivceRequestList = new List<ServiceRequest>
                {
                    new ServiceRequest
                    {
                        Req = new RequestObject
                        {
                            Input = new InputObject
                            {
                                Location = new LocationObject
                                {
                                    Name = "illes?",
                                    Type = "ALL"
                                },
                                Field = "S"
                            }
                        },
                        Method = "LocMatch"
                    }
                },
                
                Client = new ClientObject()
            };

            
            // RestSharp wundervolle Library um API request zu schicken. 
            var client = new RestClient("https://reiseauskunft.bahn.de/bin/mgate.exe");
            var request = new RestRequest
            {
                Method = Method.POST
            };
            request.AddHeader("User-Agent", "DB Navigator/19.10.04 (iPhone; iOS 13.1.2; Scale/3.00)");
            request.AddHeader("Accept-Encoding", "json");

            // Wandelt mein Objekt in nen JSON String um.
            var data = JsonConvert.SerializeObject(stationRequest);
            data = data.Replace(Environment.NewLine, "\n");

            // Bei Value sollte dann CalculateChecksum(data) verwendet werden.
            // Der jetzige wert ist der offizielle Wert der iOS App.
            request.AddQueryParameter("checksum", "f715e40d9d22a069650e67631d7ff71f");
            request.AddJsonBody(data);

            // Abfahrt.
            var response = client.Execute(request);
```

Wie du sehen kannst habe ich die checksum von der App hardcoded.
Wenn ich mein Programm so ausführe wie im Code oben, dann bekomme ich keinen Internal Server Error (bei einem "einzeiler" json string)

Sprich der checksum so wie ihr ihn generiert oder ich es mache, gilt nicht für die iOS App.
Ich habe alle Arten von tests, sowie Kombinationen zum erstellen des hashes ausprobiert.

Daher habe ich hier nachfragen wollen ob einer von euch einen Logikfehler spotten kann oder ob in der iOS App tatsächlich andere dinge passieren (eventuell anderer salt, andere checksum "formel")

**Comment by derhuerst** [comment]
> Ich versuche die API auf .NET zu porten für meinen eigenen gebrauch.

Ah, alles klar.

> Wenn ich mein Programm so ausführe wie im Code oben, dann bekomme ich keinen Internal Server Error (bei einem "einzeiler" json string)

Das klingt aber so, als würde in der tat ein Ein*zeiler* generiert werden, d.h. ohne Zeilenumbrüche und Einrückung. Diese Zeichen sind aber anderer Input für einen Hashing-Algorithmus, wie ich in https://github.com/public-transport/hafas-client/issues/137#issuecomment-541926172 dargestellt habe.

Hast du überprüft, dass du via `JsonConvert.SerializeObject(stationRequest)` exakt dieselben Zeilenumbrüche, selbe Einrückung und selbes Encoding erhälst, wie die App für die Berechnung der Prüfsumme verwendet?

Ich habe dir vorgeschlagen, gegen eine der existierenden Open-Source-Implementierungen zu entwickeln, **weil du dann dort Stück für Stück verifizieren kannst, ob alle Schritte richtig sind, und nicht einfach nur am Ende aus der App ein Hash rausfällt**. Ich habe leider weder die Zeit noch das C#-Wissen, um dir mit deiner Implementierung *konkret* zu helfen.

**Letztendlich musst du ja nicht genau dieselbe Formatierung (und damit dieselbe Prüfsumme) *der App* berechnen, sondern nur *irgendeine*, bei der die Prüfsumme passt.**

Mein Vorschlag:

Es gibt z.B. bei [`repl.it`](https://repl.it) oder [Glitch](https://glitch.com/) Online-Umgebungen, in denen du Node.js- und Java-Code ausführen kannst. **Installier dir da `hafas-client`/`public-transport-enabler` und bau an den richtigen stellen debug-logs ein**, dann kannst du deine Implementierung *Stück für Stück* dagegen vergleichen.

**Comment by derhuerst** [comment]
Wenn du übrigens einen C#-Hafas-Client baust, wäre es sehr toll, wenn du den Open Source machst. Dann können andere auch davon profitieren! 💛

**Comment by Logxn** [comment]
> Hast du überprüft, dass du via JsonConvert.SerializeObject(stationRequest) exakt dieselben Zeilenumbrüche, selbe Einrückung und selbes Encoding erhälst, wie die App für die Berechnung der Prüfsumme verwendet?

Das kann ich nicht exakt überprüfen.
Ich benutze die App "Charles" für iOS um die Requests zu sniffen.
Da ist leider kein Raw input dabei

> Es gibt z.B. bei repl.it oder Glitch Online-Umgebungen, in denen du Node.js- und Java-Code ausführen kannst. Installier dir da hafas-client/public-transport-enabler und bau an den richtigen stellen debug-logs ein, dann kannst du deine Implementierung Stück für Stück dagegen vergleichen.

Werde das nochmal probieren und hoffentlich mit einer Aussagekräftigen Antwort zurückkommen.

> Wenn du übrigens einen C#-Hafas-Client baust, wäre es sehr toll, wenn du den Open Source machst. Dann können andere auch davon profitieren! 💛
Das ist der Plan! 

Hoffe das ich die Tage die iPhone App gedumped von nem Kollegen bekomme und reversen kann.
Dann kann dieses mysterium (falls sich Android & iOS hashing tatsächlich unterscheiden sollten) geklärt werden

**Comment by derhuerst** [comment]
> Hoffe das ich die Tage die iPhone App gedumped von nem Kollegen bekomme und reversen kann. Dann kann dieses mysterium (falls sich Android & iOS hashing tatsächlich unterscheiden sollten) geklärt werden

Dafür ist @juliuste auch häufig zu haben. 😁

**Comment by derhuerst** [comment]
Ich schließe dieses Issue für mehr Übersichtlichkeit. Bitte öffne es wieder, wenn das Problem für dich weiterhin besteht.

**Comment by derhuerst** [comment]
>> Wenn du übrigens einen C#-Hafas-Client baust, wäre es sehr toll, wenn du den Open Source machst. Dann können andere auch davon profitieren! 💛
>
> Das ist der Plan!

Wie sieht's aus? 😉
