### ISSUE TITLE
Improve find-in-tree.js

### ISSUE THREAD

**Issue by simlu** [public-transport/hafas-client#146]
- object-scan has a callback method "filterFn" that exposes the parent (no need to loop through the results again)
- object-scan has a "joined" flag, so there is no need to use lodash toPath

https://github.com/public-transport/hafas-client/blob/42b2a8a7bfd163504317279b967aa64e81996247/lib/find-in-tree.js#L14

**Comment by simlu** [comment]
Something like
```js
const findInTree = (tree, selector, onResult) => {
  scanner([selector], {
    joined: false,
    filterFn: (key, value, { parents }) => {
      onResult(value, parents[0], key);
    }
  })(tree);
}
```
(untested)

**Comment by derhuerst** [comment]
PR welcome!

> (untested)

The tests should tell you wether you broke it. 😉

**Comment by simlu** [comment]
@derhuerst Would be great if you could set up CI, so I can do it and test right through Github 😉

**Comment by simlu** [comment]
I've created the pr. How do we get Travis to run against it?

**Comment by simlu** [comment]
@derhuerst Pr is up 👍 Looks like there is no eslint test (the formatting I've used should probably fail) and the e2e test also failed?

Please do take a look
