### ISSUE TITLE
Consider using nock for e2e tests

### ISSUE THREAD

**Issue by simlu** [public-transport/hafas-client#148]
Consider using [nockBack](https://github.com/nock/nock#readme) for e2e test. We a very convenient wrapper for mocha called [node-tdd](https://github.com/blackflux/node-tdd#usenock).

The way this would work:
1. Run tests against external apis as necessary, nockBack / node-tdd automatically captures requests and stores them in cassettes
2. Re-running the tests will not make external requests. Instead the request is intercepted and the recording is returned. So if the external service is temporarily unavailable or slow, this wont impact test success. No external requests should ever be made when test are run as part of a suite
3. When a service changes their API, delete the recordings for the relevant tests and re-run the tests (fix code as necessary). Then commit the new cassettes

This is a solid approach when dealing with external APIs and considered best practice.

**Comment by derhuerst** [comment]
> Consider using [nockBack](https://github.com/nock/nock#readme) for e2e test.

Sounds great! I agree that this will make the E2E tests more meaningful and reliable.

Keep in mind that we will have to use the [`lodash/matches` variant](https://github.com/nock/nock/tree/c7363e56ee866635514e5aaa0319232b6edd1b61#specifying-request-body) when matching the request.

> We a very convenient wrapper for mocha called [node-tdd](https://github.com/blackflux/node-tdd#usenock).

I'm not really a fan of mocha, sorry. I think we can use [`tape-nock`](https://github.com/Flet/tape-nock) though.

> No external requests should ever be made when test are run as part of a suite

The HAFAS APIs change so often that it still makes sense to have an "isolated" CI run that checks if they still match. Sort of like a monitoring system.

**Comment by derhuerst** [comment]
In #148, I ended up using [`replayed`](https://github.com/aneilbaboo/replayer), because I didn't like the way `tape-nock` grouped recorded requests by test name.

Having made the E2E more deterministic, it now works well!
