### ISSUE TITLE
parse potentially recursive locL[] items

### ISSUE THREAD

**Issue by derhuerst** [public-transport/hafas-client#151]
When trying to parse the stop/station & entrances hierarchies exposed by some HAFAS endpoints (#131), I noticed that parsing the items in `res.common.locL` is potentially recursive.

The data seen so far (e.g. [from the HVV endpoint](https://gist.github.com/derhuerst/5a9d29a556b54182f9d30202f7244bfd#file-location-http-L218-L229)) wasn't recursive, but it might occur. How do we parse them properly?

So far, I see a two-step parsing process:

1. resolve references (e.g. `stopLocL[].locX`) with "placeholder" objects for the to-be-parsed locations
2. parse `locL`, let `parseLocation` assign its output to the respective "placeholder" object

This has several disadvantages:

- The whole process becomes a lot harder to understand from reading the code.
- Cycles in the result may break consuming libraries that try to serialise the output (for example, [`JSON.stringify` fails with cycles](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value)).
- It will be easy to break the mechanism by overriding `parseLocation` in a profile, with a function that returns a *new* object instead of assigning to the "placeholder".

How would/did you solve this @marudor @alexander-albers @schildbach ?

**Comment by derhuerst** [comment]
> So far, I see a two-step parsing process:

resolve references with "placeholder" objects for the to-be-parsed locations
parse locL, let parseLocation assign its output to the respective "placeholder" object


Different solution:

1. resolve references with a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Description),
2. keep track of all `parseLocation` return values in a map/list,
3. let the getters access the list.

This way, there are no "placeholder" objects, but the other problems still apply.

**Comment by schildbach** [comment]
Public-transport-enabler parses these records recursively: https://github.com/schildbach/public-transport-enabler/blob/939b4fcbc3c3f988d5515d0ee52811cebbe77621/src/de/schildbach/pte/AbstractHafasClientInterfaceProvider.java#L1026-L1029

The tricky part is ending the recursion, as you can see the end condition checks for cycles. I think the open question is if such a cycle occurs, as there is no "leaf" which of the record is best used as the station record?

**Comment by schildbach** [comment]
I'm curious at what solution you come up with, mainly in terms of a proper data model.

**Comment by derhuerst** [comment]
Closing. AFAIR #153 covers all real-world use cases for recursive `locL` items that I'm currently aware of.
