### ISSUE TITLE
DB: LoadFactor in JourneyLeg not parsed

### ISSUE THREAD

**Issue by bergmannjg** [public-transport/hafas-client#156]
The loadfactor in a journey leg ist not parsed.

The problem is probably in p/db/index.js:
https://github.com/public-transport/hafas-client/blob/fd3bc17d08c399f6fb55bd374698b9b698856eb7/p/db/index.js#L119

maybe *tcocL* should be used like here:
https://github.com/public-transport/hafas-client/blob/fd3bc17d08c399f6fb55bd374698b9b698856eb7/p/db/index.js#L47

**Comment by derhuerst** [comment]
Thanks for reporting!

**Comment by bergmannjg** [comment]
Thank you for this awesome tool

**Comment by derhuerst** [comment]
If you use this library a lot or even rely on it, especially in a professional context, consider sponsoring me [via GitHub Sponsors](https://github.com/sponsors/derhuerst) or [via Patreon](https://patreon.com/derhuerst). 💚

**Comment by derhuerst** [comment]
Published as `hafas-client@5.1.2`. 🎉
