### ISSUE TITLE
Direction field for arrivals is always null

### ISSUE THREAD

**Issue by marzieh-kazemi** [public-transport/hafas-client#179]
The `direction` field for arrivals return always null for any trip. @derhuerst @juliuste :)

The version we use => ^5.0.2

<img width="635" alt="Screenshot 2020-06-08 at 12 44 34 PM" src="https://user-images.githubusercontent.com/41323375/84127864-0f53cb00-aa40-11ea-811e-b0eabee73679.png">

**Comment by derhuerst** [comment]
This is due to 044a5ee816d1ba97beef0687bc38b1e5e5c53b94. HAFAS does not seem to return the direction (as in where the trip will end) for arrivals, but instread just where the trip started.

We should expose that information though. PR welcome!

**Comment by marzieh-kazemi** [comment]
But we don't get where the trip started, I thought it will be covered by direction like departure? What is the field for it then?

**Comment by juliuste** [comment]
I'd suggest adding a field `provenance` for arrivals then, which contains this value. This is very useful to have e.g. for an departures/arrivals board.
