### ISSUE TITLE
No polyline with trip method

### ISSUE THREAD

**Issue by jonasgaiswinkler** [public-transport/hafas-client#181]
I tried to use `trip()` with the `polyline: true` option with the `oebb` profile, but no polyline is returned. The http request returns the polyline, but it seems like it doesn't get parsed. The same applies to the `svv` profile.

**Comment by jonasgaiswinkler** [comment]
Thank you for the bugfix and this fantastic library!

**Comment by derhuerst** [comment]
If you want to support this project, especially if you use it professionally, please consider [supporting me](https://mobile.twitter.com/elizab0t/status/1271034842118004740) (there will be a project-specific sponsoring option soon).

**Comment by derhuerst** [comment]
Published as `hafas-client@5.6.2`.
