### ISSUE TITLE
add SBB profile (swiss rail)

### ISSUE THREAD

**Issue by noerw** [public-transport/hafas-client#197]
SBB operates a HAFAS endpoint: http://fahrplan.sbb.ch/bin/mgate.exe

Sidenote: SBB leads by example and provides [open transit data](https://opentransportdata.swiss/de/dataset). Still it may be useful to query their HAFAS

**Comment by derhuerst** [comment]
> SBB operates a HAFAS endpoint: https://fahrplan.sbb.ch/bin/query.exe

This URL usually *doesn't* support the mobile API. [`public-transport-enabler` also doesn't use a mobile endpoint for SBB.](https://github.com/schildbach/public-transport-enabler/blob/286e1718bff643056dc6b9a0a19e0a9a197eaf0a/src/de/schildbach/pte/SbbProvider.java)

@juliuste Do you know if there's a mobile API endpoint?

**Comment by marudor** [comment]
@derhuerst https://github.com/marudor/BahnhofsAbfahrten/blob/main/packages/server/HAFAS/profiles.ts#L344

**Comment by noerw** [comment]
Great! I'll try that config and if it works come back with a PR :)

**Comment by derhuerst** [comment]
Closing because #202, successor of #198, is merged.

**Comment by derhuerst** [comment]
Published as `hafas-client@5.13.0`. 🎉
