### ISSUE TITLE
Add product filtering to departures

### ISSUE THREAD

**Issue by gaudes** [public-transport/hafas-client#212]
Hi Janis,

is it possible to add filtering for products in the departures function?

You've already planed it, as written in the documentation :-)

https://github.com/public-transport/hafas-client/blob/master/docs/departures.md

Thanks and regards,

Ralf

**Comment by derhuerst** [comment]
Thanks for reporting!

Turns out that `departures()`/`arrivals()` already support `opt.products`. In 92f1831, I have added documentation.

Let me know if you have further questions.
