### ISSUE TITLE
Problem with NPM version 10

### ISSUE THREAD

**Issue by gaudes** [public-transport/hafas-client#219]
Hi Jannis,

since your new version 5.15.1 there is a problem with a dependency:

```
Unsupported engine for object-scan@13.9.2: wanted: {"node":">= 12"} (current: {"node":"10.24.0","npm":"6.14.11"})
```

But your package.json has minimal version 10:

```
	"engines": {
		"node": ">=10"
	},
```

I still have a few users running Node 10.

Is it possible to support Node 10 again ?

If not, I will set the engine in my package.json to version 12.

Thanks and regards,

Ralf

**Comment by derhuerst** [comment]
Thanks for reporting!

This can be considered a bug, it's not intended. Will downgrade object-scan.

**Comment by derhuerst** [comment]
Thanks to @simlu 's awesome response time and cooperation, it will we fixed very soon:

https://github.com/blackflux/object-scan/commit/55c9dcb4e66fdfa79409d4a71cbc54b1a51789fa#commitcomment-48014705

**Comment by gaudes** [comment]
Chain of dependencies :-)
Thanks, I'll wait for a new version

**Comment by simlu** [comment]
@gaudes ok, should be fixed. Sorry about that... I'm rolling node 10 deprecation out again as a breaking change now (major version bump).

**Comment by derhuerst** [comment]
@gaudes An `npm upgrade` (npm 7) or `npm upgrade --depth 2` (npm 6) should fix it.

Pleqse reopen if you still have problems with this.

**Comment by gaudes** [comment]
Works again :-) 

I've found the problem with an automated testing in a GitHub Workflow, just for information.

So I've just re-run the job in GitHub and now everything is fine again :-)

Thank you very much for your fast solution.

Best regards, Ralf
