### ISSUE TITLE
BahnCard 1st class not selectable

### ISSUE THREAD

**Issue by roehrt** [public-transport/hafas-client#221]
Hey there,

In https://github.com/public-transport/hafas-client/blob/68d8bf9fca31de0608b5ba7b7dbdb57a96a33a59/p/db/loyalty-cards.js#L17-L18 `c.class` always seems to be `undefined`, which means that the BahnCard 2nd class is always used. This is problematic because it means there is no BahnCard discount when booking 1st class trips.

I would suggest to either replace `c.class` with `data.class` which allows the user to choose the class of the BahnCard or use `firstClass` from `opt` to provide information about class.

Also https://github.com/public-transport/hafas-client/blob/68d8bf9fca31de0608b5ba7b7dbdb57a96a33a59/p/db/loyalty-cards.js#L5 contains a typo (`loyaly`).

Thank you in advance!

**Comment by derhuerst** [comment]
Thanks for reporting! A PR that fixes both issues would be great.
