### ISSUE TITLE
Problems with OEBB profile

### ISSUE THREAD

**Issue by gaudes** [public-transport/hafas-client#225]
Hi Jannis,

looks like OEBB has made a broken change again.

Users get the following error:

invalid json response body at https://fahrplan.oebb.at/bin/mgate.exe? reason: Unexpected token < in JSON at position 0

Can you check, please ?

Thanks and kind regards,

Ralf

**Comment by derhuerst** [comment]
Thanks for reporting!

**Comment by derhuerst** [comment]
> ```
> invalid json response body at https://fahrplan.oebb.at/bin/mgate.exe? reason: Unexpected token < in JSON at position 0
> ```

Are you sure this happens at `https://fahrplan.oebb.at/bin/mgate.exe?`? I could only reproduce the problem with `http://fahrplan.oebb.at/bin/mgate.exe?` (note the `http:`) and apparently fixed it by switching to `https:`.

**Comment by derhuerst** [comment]
I have published dbac565 as `hafas-client@5.15.2`. 🎉
