### ISSUE TITLE
Error when fetching data client

### ISSUE THREAD

**Issue by julianx03** [public-transport/hafas-client#230]
I have a strange problem with the OEBB profile.

Sometimes when I retrieve data from for example Villach Hbf station I get this strange error you see in the pictures and I don't know why. I have changed the products so that I only fetch the trains and I get this error, but when I only fetch the buses I don't get an error.

But when I use the DB profile for it, it works without any problems, even when I retrieve the trains. 

The funny thing is when I test it on another PC it works and then sometimes it doesn't work.

Can someone please help me?

![screen1](https://user-images.githubusercontent.com/79427312/117135798-bb647a00-ada7-11eb-8966-8c6711b89883.PNG)

used the parameter --unhandled-rejections=strict when running node
![screen2](https://user-images.githubusercontent.com/79427312/117135800-bbfd1080-ada7-11eb-8fb6-938038c7d413.PNG)

**Comment by derhuerst** [comment]
Please also provide your code, in the smallest version that still reproduces the problem.

**Comment by derhuerst** [comment]
> used the parameter `--unhandled-rejections=strict` when running node

Most likely, in your calling code, you're using an [`async`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) (or [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)-returning, that's basically the same) function without `await` or `.catch()`.

The best way to handle the error depends on your use case: You may just log it (`.catch(console.error)`), you may also exit the process (`process.exit(1)`), you may show it to the user in some other form, you may retry the request.

**Comment by julianx03** [comment]
Here is the code, what im using. 

I'm using hafas-client 5.16.0

[index2.zip](https://github.com/public-transport/hafas-client/files/6433028/index2.zip)

**Comment by julianx03** [comment]
This error happens, when i fetch data from a Train Station (for example Villach Hbf) and then only fetch the trains. When i fetch only busses it works just fine.

**Comment by derhuerst** [comment]
I cannot reproduce the problem. Right now, this script doesn't crash for me:

```js
const createClient = require('hafas-client');
const oebbProfile = require('hafas-client/p/oebb');

const client = createClient(oebbProfile, 'my-awesome-program');

client
.departures('8100147', {
	duration: 1800, //TIME
	products: {
		tram: false,
		ferry: false,
		bus: false,
		interregional:true,
		national: true,
		nationalExpress:true,
		suburban: true,
	},
	results: 10,
})
.catch(console.error)
```

**Comment by derhuerst** [comment]
Please run your script with the `DEBUG` environment variable set to `hafas-client`. It will print the full raw request and raw response then.

**Comment by julianx03** [comment]
I have tried again, now the error is gone. I don't know why.

**Comment by derhuerst** [comment]
When you stumble upon this error again, don't hesitate to run your code with `DEBUG=hafas-client` and post the request & response here.
