### ISSUE TITLE
Expose `realtimeDataFrom` for refreshJourney

### ISSUE THREAD

**Issue by yu-re-ka** [public-transport/hafas-client#239]
`journeys()` returns a `realtimeDataFrom`, but `refreshJourney()` does not, even though the data is in the raw response

**Comment by derhuerst** [comment]
PR welcome!

Let's just expose it as `journey.realtimeDataFrom` for now, and change `refreshJourney()`'s return value to an object `{journey, realtimeDataFrom}` with the next major release (#86).
