### ISSUE TITLE
Filter arrivals() by mode of transportation

### ISSUE THREAD

**Issue by flixxgamez** [public-transport/hafas-client#255]
A way to filter out modes of trainsportation e.g. buses in die arrivals() method.

**Comment by flixxgamez** [comment]
Checkt the docs a seconde time and found the way to overwrite there.

**Comment by derhuerst** [comment]
Correct, `arrivals()` works like `departures()`, so [you can use `products: {every: false, other: false, product: false, bus: true}`](https://github.com/public-transport/hafas-client/blob/5/docs/departures.md).
