### ISSUE TITLE
DB profile: disappearing delays in past arrivals 

### ISSUE THREAD

**Issue by flixxgamez** [public-transport/hafas-client#256]
When requesting data using the DB profile and the `arrivals()` method, information on the delay is missing. For example: 
Normal: `when: '2022-01-08T22:46:00+01:00',
    plannedWhen: '2022-01-08T22:46:00+01:00',
    delay: 0,` for ICE 702 
Missing: `    when: '2022-01-08T22:05:00+01:00',
    plannedWhen: '2022-01-08T22:05:00+01:00',
    delay: null,` for ICE 653 

I think this problem be could by caused after a train left the station. For past delays the HAFAS method 'SearchOnTrip' may be useful (not sure tho).

**Comment by derhuerst** [comment]
> When requesting data using the DB profile and the `arrivals()` method, information on the delay is missing. [...] I think this problem be could by caused after a train left the station.

I have observed this as well, and it seems like this is the usual behaviour of the DB endpoint.

This is of course wild speculation, but I'd guess that it has to do either with technical limitations in their backend, or with a policy not to expose past/historical delay data.

> For past delays the HAFAS method `SearchOnTrip` may be useful (not sure tho).

`SearchOnTrip ` is called [`journeysFromTrip`](https://github.com/public-transport/hafas-client/blob/5/docs/journeys-from-trip.md) in `hafas-client`. You're very welcome to check if it returns past/historical delays, but at least its use case is a different one.

**Comment by derhuerst** [comment]
remotely related: https://github.com/iRail/iRail/issues/497
