### ISSUE TITLE
DB profile: stopovers not working in arrivals()

### ISSUE THREAD

**Issue by flixxgamez** [public-transport/hafas-client#258]
When checking for arrivals using the DB profile and setting `stopovers: true` to get past stops, I get a error:

> Error: opt.stopovers is not supported by this endpoint

**Comment by derhuerst** [comment]
True, with the DB profile, `stopovers: true` doesn't work for both `departures()` and `arrivals()`. This is because the HAFAS endpoint doesn't support the `getPasslist` flag.

So far, I haven't found a replacement flag, but maybe there is.
