### ISSUE TITLE
Why does trip() require lineName?

### ISSUE THREAD

**Issue by yu-re-ka** [public-transport/hafas-client#269]
It doesn't seem to matter what I pass there, is there some example where the tripId is not sufficient, maybe it is different on some endpoints?

**Comment by derhuerst** [comment]
It used to matter: At some point in the past, HAFAS didn't respond to `trip()` calls with the proper line name, except if you passed it in.

This is not the case anymore, the `lineName` parameter just exists for backwards-compatibility, and will be removed in `hafas-client@6` (#265).

**Comment by derhuerst** [comment]
Please re-open if you have more related questions.
