### ISSUE TITLE
/journeys invalid poi

### ISSUE THREAD

**Issue by vidkazan** [public-transport/hafas-client#299]
Hi! 

I make /journey request with valid POI from API documentation, and receive "invalid poi" from server:

**Request:**
`https://v6.db.transport.rest/journeys?from.id=991592571&from.latitude=50.769349&from.longitude=6.09537&to=8089222` 

**Response:**
`{
	"message": "invalid POI"
}`

**Screenshot:**
<img width="922" alt="Screenshot 2023-10-18 at 14 50 08" src="https://github.com/vidkazan/49EuroTravel_SwiftUI/assets/33557107/ccf82c77-80ea-4dee-bc23-1c757ce2cdff">

**Comment by derhuerst** [comment]
Thanks for reporting!

This is actually an issue with the [`db-rest#6`](https://github.com/derhuerst/db-rest/tree/6) docs. (But I [can't transfer this Issue to the `db-rest` repo](https://github.com/orgs/community/discussions/5766).)

Unfortunately, for legacy reasons, `hafas-client@6` imposes a limitation onto the API: **You need to pass `from.name=…` too**, but ironically, you can pick any value for it.

I have fixed this in https://github.com/derhuerst/db-rest/commit/8482862f769fb6ed030223d8b7837190bb9229ab.
