### ISSUE TITLE
refreshToken: always returns 404 from/to Köln/Bonn Flughafen station

### ISSUE THREAD

**Issue by vidkazan** [public-transport/hafas-client#312]
# to Köln/Bonn Flughafen
**request:** 
https://v6.db.transport.rest/journeys/T$A=1@O=Köln%20Hbf@L=8000207@a=128@$A=1@O=Köln/Bonn%20Flughafen@L=8003330@a=128@$202401241401$202401241415$S%2019$$1$$$$$$

**response:**
Cannot GET /journeys/T$A=1@O=K%C3%B6ln%20Hbf@L=8000207@a=128@$A=1@O=K%C3%B6ln/Bonn%20Flughafen@L=8003330@a=128@$202401241401$202401241415$S%2019$$1$$$$$$

# from Köln/Bonn Flughafen
**request:** 
https://v6.db.transport.rest/journeys/T$A=1@O=Köln/Bonn%20Flughafen@L=8003330@a=128@$A=1@O=Köln%20Hbf@L=8000207@a=128@$202401241409$202401241423$RB%2010618$$1$$$$$$

**response:**
Cannot GET /journeys/T$A=1@O=K%C3%B6ln/Bonn%20Flughafen@L=8003330@a=128@$A=1@O=K%C3%B6ln%20Hbf@L=8000207@a=128@$202401241409$202401241423$RB%2010618$$1$$$$$$

**Comment by derhuerst** [comment]
You must URL-encode (a.k.a. percent-encode) the `/` inside the journey's reconstruction context as `%2F`.

**Comment by vidkazan** [comment]
Got it. Thank you:)
