### ISSUE TITLE
journeys(): Canceled journeys are missing in API response (DB)

### ISSUE THREAD

**Issue by Krystex** [public-transport/hafas-client#328]
Hi all ✋ 
First of all thanks to the creator and maintainer for this projects, it's immensely helpful!

The problem I encountered: When comparing the results of https://www.bahn.de/ or DB Navigator and hafas-client, somehow canceled journeys are omitted in the API response:

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/6ec5c9e7-960f-4bc0-aa2c-9bf5c77cccfa">

```js
const res = await client.journeys('8010085', '8011160', {results: 10, transfers: 0, tickets: true})
for (const journey of res.journeys) {
  const leg = journey.legs[0]
  console.log(`${leg.plannedDeparture} ${leg.line.name}`)
}
```
results in:
```
2024-11-10T16:54:00+01:00 EC 172
2024-11-10T18:54:00+01:00 EC 170
2024-11-10T19:54:00+01:00 RJ 256
2024-11-10T20:30:00+01:00 ES 452
2024-11-11T06:00:00+01:00 NJ 456
2024-11-11T06:22:00+01:00 FLX 1230
```

Am I missing a flag or is the API response malformed?

**NOTE**: If you read this, the journeys probably don't exist anymore. You can find canceled trips over the [DB Verkehrsmeldungen Page](https://www.bahn.de/service/fahrplaene/aktuell)

**Comment by dabund24** [comment]
Have you tried modifying the `routingMode` option? (see https://github.com/public-transport/hafas-client/tree/main/p/db#using-the-routingmode-option )

**Comment by Krystex** [comment]
Thanks for the help, with `routingMode` `FULL` it is working with the hafas-client library!

However I'm actually using the [db-rest API](https://v6.db.transport.rest/) and the `routingMode` parameter is not documented in [/journeys](https://v6.db.transport.rest/api.html#get-journeys) and doesn't work when I specify it. 

Should I create an issue there? I can try to fix the problem myself but I'm not familiar with the codebase yet.

**Comment by Krystex** [comment]
No rush, thank you so much for your work!
