### ISSUE TITLE
[v5.db.transport.rest] SSL Protocol Error – Link Not Working

### ISSUE THREAD

**Issue by ahmadhash** [public-transport/hafas-client#329]
Firstly, thank you to the creator and maintainer for the great work on this library! It has been incredibly useful, and I really appreciate the effort put into keeping it up and running.

However, I've encountered an issue with the link https://v5.db.transport.rest/, which was working fine last week but is currently inaccessible. When trying to access the site, the following error is encountered:

```
This site can’t provide a secure connection
v5.db.transport.rest sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

![Screen Shot 2024-11-11 at 8 39 12 PM](https://github.com/user-attachments/assets/b3734646-a56b-414b-8fc7-22dbd715fcf9)

Steps to Reproduce:
- Navigate to https://v5.db.transport.rest/
- The error occurs immediately upon page load.

**Comment by traines-source** [comment]
Thanks for reporting, this should be fixed now.

**Comment by derhuerst** [comment]
@ahmadhash Note that the https://v5.db.transport.rest API has been deprecated for over a year. Please use https://v6.db.transport.rest.
