### ISSUE TITLE
remove journey.departure, journey.origin, etc

### ISSUE THREAD

**Issue by derhuerst** [public-transport/hafas-client#36]
As discussed with @juliuste this is redundant information not specified in FPTF and therefore reduces the compatibility with other FPTF libraries.

**This is a breaking change.**

**Comment by juliuste** [comment]
See [friendly-public-transport-format#34](https://github.com/public-transport/friendly-public-transport-format/issues/34) as well.

**Comment by derhuerst** [comment]
This PR also fixes the tests on `next`. 😬 (Sorry for not properly creating.)

**Comment by juliuste** [comment]
We should also update the docs.

**Comment by derhuerst** [comment]
> We should also update the docs.

Done as of 2430a74.

**Comment by derhuerst** [comment]
This can be closed, right?
