### ISSUE TITLE
departures: expose arrivals, possibly rename the method

### ISSUE THREAD

**Issue by derhuerst** [public-transport/hafas-client#38]
Right now, it's not possible to get arrivals, but they may differ significantly from the departure times.

@juliuste what do you think would be an intuitive method for getting both departures *and* arrivals (at once)? "station board", as used be HAFAS APIs doesn't seem to be very appropriate.

**Comment by juliuste** [comment]
I've encountered the method name `timetable` in several other APIs and it seems quite fitting to me.

**Comment by juliuste** [comment]
See also: [this article](https://en.wikipedia.org/wiki/Public_transport_timetable).

**Comment by derhuerst** [comment]
"timetable" is definitely better than "station board" or "departures", but sounds very scheduled to me. There are APIs without any scheduled departures/arrivals.

**Comment by derhuerst** [comment]
#65 added the `arrivals()` method. I think it makes sense to keep it separate from `departures()` to keep the 1-to-1 mapping between `hafas-client` calls and HTTP requests (with one exception).
