### ISSUE TITLE
Undefined variable d

### ISSUE THREAD

**Issue by soldatos** [public-transport/hafas-client#43]
Hey @all,

where is the variable d defined? I received a undefined error on this line. 

> hafas-client/parse/stopover.js

The line:

`const arr = profile.parseDateTime(profile, d.date, st.aTimeS)`

Complete lines:

`if (st.aCncl) {
				res.arrival = res.arrivalDelay = null
				const arr = profile.parseDateTime(profile, d.date, st.aTimeS)
				res.formerScheduledArrival = arr.toISO()
			}
			if (st.dCncl) {
				res.departure = res.departureDelay = null
				const arr = profile.parseDateTime(profile, d.date, st.dTimeS)
				res.formerScheduledDeparture = arr.toISO()
			}`

**Comment by juliuste** [comment]
Hey (:
Thank you for reporting this issue! 🙂 Will have a look at it. Which profile, method and options did you use when you got the error?

**Comment by soldatos** [comment]
Hi @juliuste ,

i use the db profile: `const dbProfile = require('hafas-client/p/db')`

I got this error only if the leg is canceled. The problem is on the whole line because canceled legs did not have arrival or departure times to parse. After i changed the line to: `const arr = profile.parseDateTime(profile, date, st.aTimeS)` 
 i got the next error:
> 'substr' is undefined. 

Here an excerpt from the API Doc:

> If a journey leg has been cancelled, a cancelled: true will be added. Also, departure/departureDelay/departurePlatform and arrival/arrivalDelay/arrivalPlatform will be null.

And thank you for the great work!

**Comment by derhuerst** [comment]
> After i changed the line to: `const arr = profile.parseDateTime(profile, date, st.aTimeS)` i got the next error:
>
>> 'substr' is undefined.

Please try running your code with `env NODE_ENV=dev node your-script.js` and provide the full stack trace.

**Comment by derhuerst** [comment]
I have released `hafas-client@2.5.1`, which contains a fix for the first issue.

@juliuste We should definitely add tests for this on `next`.

**Comment by soldatos** [comment]
@derhuerst and @juliuste  thank you!

I found the problem. I got the error only if the journey are canceled and the following options are set:

`client.journeys(startStation, endStation , {results: 6, passedStations: true, tickets: false}`

**The option** ...
> passedStations: true
... get all stations between two stops. 

But canceled journeys have not times.

> If a journey leg has been cancelled, a cancelled: true will be added. Also, departure/departureDelay/departurePlatform and arrival/arrivalDelay/arrivalPlatform will be null.

**And now the problem:**
The journey are canceled and in the following line we send time st.aTimeS (which are undefined/null) to the Method parseDateTime

`const arr = profile.parseDateTime(profile, date, st.aTimeS)`

**And the result:**
The method parseDateTime try to substr the undefined time(st.aTimeS) and send a exeption.

**Comment by derhuerst** [comment]
@soldatos If you happen to get a cancelled departure/journey again, please copy the data from the API. You could for example insert a `console.error(require('util').inspect(departure, {depth: null}))` at https://github.com/public-transport/hafas-client/blob/c8a144427e011e54a69927604bdc02d34b947aef/parse/departure.js#L34 and at https://github.com/public-transport/hafas-client/blob/c8a144427e011e54a69927604bdc02d34b947aef/parse/journey-leg.js#L77 .

**Comment by derhuerst** [comment]
By now a lot of the code base has changed. I've just fetched a cancelled journey and things seem to work fine.

Please reopen if you encounter this or a similar issue.
