### ISSUE TITLE
Change timestamp of journey

### ISSUE THREAD

**Issue by martindotlindner** [public-transport/hafas-client#51]
I want to change the timestamp of a journey using the `opt` 'when'. I guess its UNIX timestamp format, but I only got an error massage back when I enter e.g. `when: 1526821200`. What is the correct way to change the departure time of a journey?
Thanks!

**Comment by derhuerst** [comment]
You need to use a `Date` object for now. In your case, you can pass `new Date(1526821200 * 1000)`.

I think it would be good to

- validate the input and give helpful error messages
- accept anything that `new Date(…)` can parse

**Comment by martindotlindner** [comment]
I just didn't know that the `Date` object is Unix time in milliseconds and not seconds, that was the reason for the error. Many thanks!
