### ISSUE TITLE
Planning support of non-JSON endpoint?

### ISSUE THREAD

**Issue by ialokim** [public-transport/hafas-client#67]
First of all, thank you very much for your work on this project which I consider very useful.

I wanted to add support for the [saarfahrplan.de](http://www.saarfahrplan.de)-API which also uses HAFAS, but it turns out the app isn't using the *mgate.exe* endpoint, but the (older?) *query.exe* one which does not return pretty JSON data, but gzipped hexadecimal files. I've recorded some requests, you can find them [here](https://gitlab.com/snippets/1729449).

I've read the following in [your docs](https://github.com/public-transport/hafas-client/blob/master/docs/writing-a-profile.md):

> Note: hafas-client for now only supports the interface providing JSON (generated from XML), which is being used by the corresponding iOS/Android apps. It supports neither the JSONP, nor the XML, nor the HTML interface. If the endpoint does not end in mgate.exe, it mostly likely won't work.

Are there any plans to support other endpoints within this project? I would like to contribute on the integration!

**Comment by derhuerst** [comment]
> I wanted to add support for the saarfahrplan.de-API which also uses HAFAS, but it turns out the app isn't using the mgate.exe endpoint, but the (older?) query.exe one which does not return pretty JSON data, but gzipped hexadecimal files. I've recorded some requests, you can find them here.

Yeah, we've had a look at this endpoint as well.

[The iOS app seems to query `mate.exe`, with an encrypted response.](https://gist.github.com/derhuerst/719a41524b257350bd92c455fea1d9b5) We're happy about any hint that helps us reverse-engineer this.

[The Android app seems to query `stboard.exe ` with the old XML markup.](https://gist.github.com/derhuerst/bd494452388324c83bc4ee196158fe87). The XML markup is different from the JSON markup. I think a separate, but API-compatible lib would be best.

> Are there any plans to support other endpoints within this project? I would like to contribute on the integration!

Does that related to `mgate.exe`-based endpoints? If so, then yes, we happy to get contributions like #58 and #22. We're almost done with `hafas-client@3`, but currently the code still lives in the [`next` branch](https://github.com/public-transport/hafas-client/tree/next). Have a look at the ["Writing a profile" guide](https://github.com/public-transport/hafas-client/blob/bdb9c15c7e2c2d86db838afb69000120fe90e5fb/docs/writing-a-profile.md)!

**Comment by ialokim** [comment]
> The Android app seems to query stboard.exe with the old XML markup.

That's right for departures, but in the case of a journey I couldn't get any understandable XML response...

> Does that related to mgate.exe-based endpoints?

My question was referring to endpoints not using `mgate.exe`.

>  I think a separate, but API-compatible lib would be best.

Do you think this would be a good way to go if the iOS app already uses the `mgate.exe` endpoint? Are there more network providers out there still sticking to the old XML markup so that it could serve for others as well?

**Comment by derhuerst** [comment]
> Do you think this would be a good way to go if the iOS app already uses the `mgate.exe` endpoint? Are there more network providers out there still sticking to the old XML markup so that it could serve for others as well?

My gut feeling says that there aren't a lot of apps using `stboard.exe` endpoints, but this is subjective. On the other hand, I've seen quite a lot of apps that use `mgate.exe` endpoints only. You might want to check [this list](https://github.com/public-transport/public-transport-apps-encryption/blob/fb94e5758704b092a8cdb7c112e3dab5f33d211c/list.md) and [this list](https://github.com/public-transport/public-transport-apps-encryption/issues/1) to estimate wether writing a client is worth it. Maybe @juliuste knows.

That aside, we're always happy to have more API clients for more systems, in more languages! Public transportation needs to stop being the patchwork mess it currently is.

**Comment by derhuerst** [comment]
Will close this. If you happen to write or use a client for the XML-based APIs, let us know.
