### ISSUE TITLE
Failed to load error on InsaProfile

### ISSUE THREAD

**Issue by jagDanJu** [public-transport/hafas-client#71]
Hey Guys,

i´am getting the following error with the InsaProfile:

`Failed to load https://reiseauskunft.insa.de/bin/mgate.exe?: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

Is there something i can do, to fix this issue?

Greetings Daniel

**Comment by derhuerst** [comment]
I assume you're trying to use `hafas-client` in the browser?

While it should work in general, the server needs to allow cross-origin requests via a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) header. The INSA API doesn't send it, so there's not way to query it from the browser directly.

Please try to convince them to enable CORS, it's an essential part of modern and open APIs.

**Comment by derhuerst** [comment]
Closing. If you get the error for a different reason, reopen.
