### ISSUE TITLE
Profile for S-Bahn München

### ISSUE THREAD

**Issue by flori-uni** [public-transport/hafas-client#74]
So far a great project. 
At the moment I try to add support for the S-Bahn München.

Problem is the mac parameter...
I extracted the following part of the app but I don't get the valid mac parameter. 😞 
https://gist.github.com/flori-uni/b51a37ba7f84d702846da22f7fc72d4c

**Comment by derhuerst** [comment]
Hey! Thanks for looking into this.

Are you taking part in the DB Hackathon summer camp right now? If yes, who are you? If not, ignore this. 😉

Will you provide a pull request with the S-Bahn München profile? I can assist in writing it, if you want. Let's make this knowledge accessible to everyone.

**Comment by derhuerst** [comment]
**Please develop against the [`next` branch](
https://github.com/public-transport/hafas-client/tree/next)!** It contains a new structure for profiles, a [*Writing a profile* guide](https://github.com/public-transport/hafas-client/blob/96c1df5c3a28c5d13274fae385333ac61108cc84/docs/writing-a-profile.md) and a more user-friendly API.

Thanks for the Gist! I'm sure it will provide some meaningful details to implement all features of this endpoint. I have the most experience with [MITM-ing the apps, as mentioned in the guide](https://github.com/public-transport/hafas-client/blob/96c1df5c3a28c5d13274fae385333ac61108cc84/docs/writing-a-profile.md#1-setup), though.

From the gist file:

> ```
> # Per GET zu schickende URL-Parameter
> GETPARAMS=ld,checksum,mic,mac
> ```

> ```
> # Authentifizierung
> HCI_AUTH_TYPE=AID
> HCI_AUTH_AID =d491MVVhz9ZZts23
> HCI_CLIENT_ID=DB-REGIO-MVV
> HCI_CLIENT_NAME=RegioNavigator
> HCI_VALIDATION=MICMAC
> HCI_CHECKSUM=7oLXInRI9b1vhNrcY6MR180v+Wv4AwbSXU/OQoXEbTg=
> ```

This means that the endpoint uses (but may not be enforcing) the authentication mechanism described in schildbach/public-transport-enabler#187.

**Comment by derhuerst** [comment]
If you want, we can chat about this. Available via Slack (after inviting you), [via Gitter](https://gitter.im/public-transport/Lobby) or [via Telegram](https://telegram.me/derhuerst).
