### ISSUE TITLE
Unknown product express

### ISSUE THREAD

**Issue by soldatos** [public-transport/hafas-client#83]
Hi, 

i want to filter now the products for the journey but received always the error "Can't connect to Hafas Error: unknown product express". It work only when i remove the line express.

This is my opt config:
`{
          suburban: true,
          subway: true,
          tram: true,
          bus: true,
          ferry: true,
          express: true,
          regional: true
        };`

did someone make the same mistake in the search? Thanks for the answer.

**Comment by soldatos** [comment]
**Solution:**

... Express is not include as filter for DB profile. I add this two following products:

national       = that means products like IC
nationalExp = that means products like ICE

Please Update the Doc to following...

`{
          suburban: true,
          subway: true,
          tram: true,
          bus: true,
          ferry: true,
          //express: true,
          regional: true,
          national: true,
          nationalExp: true
        }`

**Comment by derhuerst** [comment]
`havas-client` supports several [profiles](https://github.com/public-transport/hafas-client/blob/master/p/readme.md), which all have slightly different products. **The docs document usage with [the VBB profile](https://github.com/public-transport/hafas-client/blob/0b29f805f4f53dbe61c59bf68dbab93c2111844d/p/vbb/readme.md), so usage with other profiles varies slightly.**

Could it be that you tried to enable the `express` product with a profile that does not contain `express`? Please post your whole code.

**Comment by soldatos** [comment]
hi @derhuerst ,

you're right. I've checked it out now in p/db/product.js and find all products (also national and nationalExp). 

Thx.
