### ISSUE TITLE
journeys: supporting opt.changeTimePercent and opt.accessibility

### ISSUE THREAD

**Issue by plSln** [public-transport/hafas-client#87]
Hey,
as described in this document: https://www.bmvi.de/SharedDocs/DE/Anlage/DG/hafas-rest-api.pdf?__blob=publicationFile , there should exist a "changeTimePercent"-Parameter.

Can you tell me, where I can add more optional parameters?

Thank you!

**Comment by derhuerst** [comment]
You have posted the docs of the *HAFAS (open) REST API*, whereas `hafas-client` talks to the *mobile HAFAS API* (the URL ends in `mgate.exe`).

So it may be that `changeTimePercent`
- exists in the mobile API with the same name
- exists in the mobile API with a different name
- does not exist in the mobile API.

Where in the document is it documented?

**Comment by derhuerst** [comment]
I will have a look at wether the `mgate.exe` endpoint supports it.

**Comment by derhuerst** [comment]
I've tried to just pass `changeTimePercent` to the `mgate.exe` endpoint. It doesn't seem to be supported, at least with this name, but maybe with a different one.

You bring this forward by finding a iOS or Android HAFAS app that supports it in the UI (check this incomplete [iOS list](https://itunes.apple.com/us/developer/hacon-ingenieurges-mbh/id315497348#see-all/i-phone-apps), or search for "fahrinfo" in the App Store). I can then analyse [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) its traffic and find the name of the option.

**Comment by plSln** [comment]
Hey,
I've found 2 apps which supports that parameter: the BVG Fahrtinfo and the Nürnberg Fahrtinfo App.
![img_46d353756563-1](https://user-images.githubusercontent.com/42576323/47493074-bd503880-d84e-11e8-8912-7c076ad51966.jpeg)
![img_0736](https://user-images.githubusercontent.com/42576323/47493168-e7a1f600-d84e-11e8-8dd8-9fee40d4351f.png)

It's the configuration : "Gehgeschwindigkeit" , but I'm interested in the "Barrierefreiheit" parameter too.
Does that help you?

**Comment by derhuerst** [comment]
> I've found 2 apps which supports that parameter: the BVG Fahrtinfo [...]

Thanks, totally missed that even though I live in Berlin! Do you want to help implement this? I can tell you how. 😉 If not, I will do it.

> [...] I'm interested in the "Barrierefreiheit" parameter too.

Theoretically [`hafas-client` supports the accessibility parameter via `opt.accessibility`](https://github.com/public-transport/hafas-client/blob/0e8ed62f23d21c326ca2dbd4d400312342071578/docs/journeys.md), but there are no tests that verify that it works, and I haven't used it in a while. So please have a look if it works according to your expectations (keep in mind that HAFAS itself is not very smart regarding accessibility).

**Comment by derhuerst** [comment]
> I would really like to help you!

Thanks. I usually try to enable contributors as much as possible, in order to have a *more open* open source project, and in order to reduce my work.

Are you familiar with MITMing apps? [The guide on writing a new profile explains how it works.](https://github.com/public-transport/hafas-client/blob/0e8ed62f23d21c326ca2dbd4d400312342071578/docs/writing-a-profile.md#1-setup)

1. Try to send a request with the default value of "Gehgeschwindigkeit", and one with a non-default value.
2. Compare the two requests to find the additional/changed parameter.
3. If you succeeded, you can also submit a PR if you want (otherwise just post your findings here). [The relevant place to add it is in `index.js](https://github.com/public-transport/hafas-client/blob/0e8ed62f23d21c326ca2dbd4d400312342071578/index.js#L130-L199).

**Comment by plSln** [comment]
nice quick tutorial, I've got in to it really quick!
I've did some research and found out, that the parameter is named "gisFltrL".
default:
`gisFltrL: [{meta: "foot_speed_normal" , mode: "FB", type: "M"}]`
fast:
`gisFltrL: [{meta: "foot_speed_fast" , mode: "FB", type: "M"}]`
slow:
`gisFltrL: [{meta: "foot_speed_ slow" , mode: "FB", type: "M"}]`

In the BVG App it has the effect im looking for, so you need 2 minutes longer for 300m, if you select slow walking. So I've tested it with 2 locations in Dresden, where im living and it has no effect. Is behavior like this possible? So that parameters only working for a specific area?

**Comment by derhuerst** [comment]
> I've did some research and found out, that the parameter is named `gisFltrL`.
> - default: `gisFltrL: [{meta: "foot_speed_normal" , mode: "FB", type: "M"}]`
> - fast: `gisFltrL: [{meta: "foot_speed_fast" , mode: "FB", type: "M"}]`
> - slow: `gisFltrL: [{meta: "foot_speed_slow" , mode: "FB", type: "M"}]`

Thanks! Do you want to PR or shall I implement it?

> So I've tested it with 2 locations in Dresden, where I'm living and it has no effect, I need the same time, no matter what I select. Is behavior like this possible? So that parameters only working for a specific area?

We will try to force a connection that one can barely reach with fast walking speed, but can't reach with slow walking, and then assert that the computed connections are different.

**Comment by plSln** [comment]
[I've created a PR.](https://github.com/public-transport/hafas-client/pull/88)
