### ISSUE TITLE
support INVG (Ingolstadt)

### ISSUE THREAD

**Issue by schildbach** [public-transport/hafas-client#93]
`https://fpa.invg.de/bin/mgate.exe` uses HCI. Versions above 1.13 would likely need a mic/mac salt, otherwise an AUTH error is raised. The iOS app should have that, but I haven't got an iOS device. For details see https://github.com/schildbach/public-transport-enabler/commit/dc390eb5a407f491c14481ab9c87206ed09d0f27.

**Comment by alexander-albers** [comment]
Extracted from the Android version (INVG Fahrinfo Ingolstadt), decoded, and tested using mic/mac parameters: `ERxotxpwFT7uYRsI`.

**Comment by schildbach** [comment]
Because it looks like base64 enconding, I assume it's the salt for the checksum? But unfortunately it doesn't work for me, I still get AUTH errors with API version 1.14. Is there some actual code I could look into? Maybe a PR adding INVG to hafas-client?

**Comment by derhuerst** [comment]
@schildbach I used it as UTF8 directly, and it worked.

BTW: I'm having trouble with the products bitmask. [I've found "Busse" is `1` and "Nahverkehrszüge" is `8`](https://gist.github.com/derhuerst/d62ef79963b1f9fb86d5cb588409859a#file-05-products-txt), but what about the others?

**Comment by derhuerst** [comment]
I have built a basic, but working, INVG profile for `hafas-client` in the [`invg` branch](https://github.com/public-transport/hafas-client/tree/invg).

**Comment by alexander-albers** [comment]
> @schildbach I used it as UTF8 directly, and it worked.

Yeah, it's the value of [requestMicMacSalt in PTE](https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractHafasClientInterfaceProvider.java#L92).

> BTW: I'm having trouble with the products bitmask. [I've found "Busse" is `1` and "Nahverkehrszüge" is `8`](https://gist.github.com/derhuerst/d62ef79963b1f9fb86d5cb588409859a#file-05-products-txt), but what about the others?

According to the source code of the INVG website, it's `[.BUS, .HIGH_SPEED_TRAIN, .REGIONAL_TRAIN, .REGIONAL_TRAIN, .SUBURBAN_TRAIN, .BUS, .FERRY, .SUBWAY, .TRAM, .ON_DEMAND]` (Bus=1, High Speed Train=2, Regional=4 and so on). I'm not 100% sure about all these values, as sometimes multiple values appear to be used for the same bitmask.

**Comment by derhuerst** [comment]
> According to the source code of the INVG website, it's `[.BUS, .HIGH_SPEED_TRAIN, .REGIONAL_TRAIN, .REGIONAL_TRAIN, .SUBURBAN_TRAIN, .BUS, .FERRY, .SUBWAY, .TRAM, .ON_DEMAND]` [...].

Thanks!

> I'm not 100% sure about all these values, as sometimes multiple values appear to be used for the same bitmask.

Indeed, this is the case with some HAFAS endpoints, e.g. [with ÖBB's](https://github.com/public-transport/hafas-client/blob/f5c0e8e58a3e66b8014903b1b1ade33199ec3911/p/oebb/products.js#L15).

**Comment by schildbach** [comment]
@derhuerst According to the data I collected, INVG only uses bits 0 and 3 for their products: 0=Bus, 3=Regional train

**Comment by schildbach** [comment]
@alexander-albers micMac and checksum are two different mechanisms which can be used separately or in combination by providers.

PTE currently expects a hex-encoded string as requestMicMacSalt, see https://github.com/schildbach/public-transport-enabler/blob/master/enabler/src/de/schildbach/pte/AbstractHafasClientInterfaceProvider.java#L671

I will try to Base64-decode then Hex-encode your string and see if that works.

**Comment by schildbach** [comment]
@alexander-albers Ok, I fixed my code in e88a4983e67c9db681614fb4d2698d6f4465dca1 and used your micMacSalt in 26d1b8efa617d6b160098a18070207b185b8ce2b. Thanks for investigating!
