### ISSUE TITLE
ver >=1.21: investigate unsupported `getPasslist` option

### ISSUE THREAD

**Issue by derhuerst** [public-transport/hafas-client#95]
https://github.com/schildbach/public-transport-enabler/commit/61ed999c659a6dacc175be3fd682d3e439c88691

This applies to any `ver` `>= 1.19`. This also applies to the `stbFltrEquiv` option.

**Comment by derhuerst** [comment]
@alexander-albers Do you know if there is a >= `1.19` equivalent to these options?

**Comment by alexander-albers** [comment]
> @alexander-albers Do you know if there is a >= `1.19` equivalent to these options?

Actually, I don't even know what exactly the parameter does. I remember that it was used in getStationboard for getting the full journey of a line for each departure, but apart from that I have never thought about that parameter. And I haven't seen any error messages in v>=1.19 either (at least in TripSearch and Reconstruction). Could you maybe elaborate what the parameter was used for in hafas-client?

**Comment by derhuerst** [comment]
- Indeed, `getPasslist` lets HAFAS return the upcoming (all?) stopovers of each departure.
- `stbFltrEquiv` lets HAFAS return departures at nearby or associated stops, e.g. in groups of stops or a bus hub next to a train station.

**Comment by alexander-albers** [comment]
> Indeed, `getPasslist` lets HAFAS return the upcoming (all?) stopovers of each departure.

But what does it do in TripSearch? Does it "expand" the journey of each leg beyond its destination?

> `stbFltrEquiv` lets HAFAS return departures at nearby or associated stops, e.g. in groups of stops or a bus hub next to a train station.

Oh right, I missed that that parameter isn't available in v>=1.19 either, that's definitely a bummer.

**Comment by alexander-albers** [comment]
Here's what seems like every parameter that can be used for a StationBoard request:

<details>
<summary>Click to expand</summary>

```javascript
StationBoard: {
  req: {
    type: null,
    stbLoc: null, // json encoded location object, removed for simplicity
    dirLoc: null, // json encoded location object, removed for simplicity
    date: null,
    dateB: null,
    dateE: null,
    time: null,
    dur: null,
    per: null,
    maxJny: null,
    minDur: null,
    jnyFltrL: [
      {
        type: null,
        mode: null,
        value: null,
        meta: null,
        locIdx: null
      }
    ],
    locFltrL: [
      {
        type: null,
        mode: null,
        value: null,
        ngramm: {
          type: null,
          attr: null,
          crd: {
            x: null,
            y: null,
            z: null,
            floor: null,
            viewAlternatives: [
              {
                graphX: null,
                subGraphNodes: [
                  {
                    subGraphX: null,
                    viewNodes: [
                      {
                        viewX: null
                      }
                    ]
                  }
                ]
              }
            ]
          },
          maxDist: null,
          startIds: null,
          endIds: null,
          fTxt: null,
          prefix: null
        }
      }
    ],
    sort: null,
    pslMode: null,
    pslMaxStops: null,
    qrCode: null,
    getTrainComposition: null,
    getSimpleTrainComposition: null,
    getJnySameTime: null,
    grpMode: null,
    jid: null,
    dTimeS: null,
    aTimeS: null
  }
}
```
</details>

I've grabbed this from https://auskunft.avv.de/js/hafas_lib_module_request_hci_1-37.js.

**Comment by derhuerst** [comment]
> > Indeed, `getPasslist` lets HAFAS return the upcoming (all?) stopovers of each departure.
> 
> But what does it do in TripSearch? Does it "expand" the journey of each leg beyond its destination?

No, it just lets the server return the "passed" stopovers in each leg of each journey, not beyond their destinations.

**Comment by derhuerst** [comment]
As of a81e550f, it defaults to false anyways.
